### ISSUE TITLE
Support multiple repositories

### ISSUE THREAD

**Issue by mdio** [czechboy0/Buildasaur#12]
You asked for it. ;)

It would be nice to be able to watch multiple repositories at the same time from the same machine.
Maybe a simple approach would be to allow multiple instances of Buildasaur running at the same time.

The only problem would be the 5000 requests limit which are used up by all instances but then one could simply configure each instance to poll less frequently.

**Comment by czechboy0** [comment]
Yeah this is also a good one, actually I wrote Buildasaur with this in mind, but I just haven't built the UI for it yet. You can see [here](https://github.com/czechboy0/Buildasaur/blob/master/Buildasaur/StorageManager.swift#L20) that we load an array of Syncers, just right now only one Syncer runs at one time, but the whole architecture is built for multiple projects to be synced at the same time.

Regarding the GitHub limit, I'll investigate in #13 whether generating a new token for each synced project would help or whether it's user-based. But currently the 5000 per hour limit should be plenty, especially if you use a sync interval of 15 seconds or higher, because each sync kicks off cca `n + k` GitHub calls (where `n` is the number of open pull requests and `k` is a small constant ~ 2, mostly guessing here though). So my guess is that with a 15 sec sync interval and < 20 open pull requests, you shouldn't be hitting the rate limit. I'll look at it closer though. Let me know if you have any ideas on this topic.

**Comment by czechboy0** [comment]
Since #13 proved that the 5000ph rate limit is per user, not per token, we need to find some decent sync frequencies to keep all repositories up to date and responsive to commands/builds, while not exhausting the rate limit. Currently for 1 repo (all that is supported atm), 15 seconds is a very good sync frequency that still keeps some head room under the rate limit.

**Comment by czechboy0** [comment]
Damn, this really needs to happen. Now I have two repos I'd like to observe, [`XcodeServerSDK`](https://github.com/czechboy0/XcodeServerSDK) and `Buildasaur`. Priority high!

**Comment by stevesparks** [comment]
@czechboy0 What is the status of this issue? I have multiple repos I would like to watch.

**Comment by czechboy0** [comment]
Buildasaur doesn't yet support that, it's a feature scheduled for 1.0. I can't give you any specific dates yet, but I welcome any help through Pull Request :)

**Comment by czechboy0** [comment]
Hey @mdio, I'm happy to tell you that after 6 months I finally got to this. Multi-repo support has been merged in master and will appear in a beta later today.

Sooo... Thanks for reporting this back then! :+1:

**Comment by mdio** [comment]
Hi, @czechboy0. Thanks for pinging me.
Unfortunately, the company I developed (and used Buildasaur) for went out of business a few months ago. So I don't use Buildasaur at the moment.

But I'm happy to see that more and more people are using your cool tool and if I get back into iOS development, I'll be happy to have multi-repo support in Buildasaur. :)

**Comment by czechboy0** [comment]
Sorry to hear the first part, but :+1: for the second

**Comment by grantjk** [comment]
:beers: We've been anxiously awaiting this.... :tada:

**Comment by czechboy0** [comment]
Looking forward to all feedback, @grantjk! (and @stevesparks)
