### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Brett-Best** [czechboy0/Buildasaur#133]
When connecting to my local Xcode Server I get an SSL error.
I was able to workaround this by adding a key to the info.plist regarding App Transport Security.

I wonder if we are able to have a preference in Buildasaur to toggle this?

**Comment by czechboy0** [comment]
Yes, this will start happening with El Cap. I don't have a good solution yet - in fact, could you please fork this repo and send a Pull Request with the Info.plist edited to completely bypass ATS? Because most people have self-signed certificates on their server, so almost everyone will hit this. Thanks :+1:

**Comment by Brett-Best** [comment]
@czechboy0 yeah neither I think unless you can change the info.plist at runtime then leaving it off might be best or have two different binaries. See #134.

**Comment by czechboy0** [comment]
Fixed by #134.
