### ISSUE TITLE
Crash on Start [0.4.0, 0.5.0]

### ISSUE THREAD

**Issue by valeriomazzeo** [czechboy0/Buildasaur#143]
I am not able to run the latest version, it crashes the moment I press the start button.

From the crashlog:

```
Application Specific Information:
fatal error: Couldn't find intended platform in list of platforms: []!: file /Users/honzadvorsky/Documents/Buildasaur/Pods/XcodeServerSDK/XcodeServerSDK/API Routes/XcodeServer+Bot.swift, line 172
```

It looks like there is an hardcoded path?

**Comment by czechboy0** [comment]
This is actually an issue in XcodeServerSDK, I created this issue [there](https://github.com/czechboy0/XcodeServerSDK/issues/114) (subscribe to that one). I'll take a look at how to nicely handle this case, but basically this means that the Bot can't be created because _no supported platforms_ were found on Xcode Server. Maybe try to reinstall Xcode Server (through OS X Server). Either way, this probably shouldn't be a crash.

**Comment by valeriomazzeo** [comment]
Do you have any idea on how to make it work? 

I have updated Xcode server to 5.0.4 and all works fine to be fair, apart from Buildasaur.

**Comment by czechboy0** [comment]
So when you're creating a Bot (manually, from Xcode), does it let you select devices to test on?

**Comment by valeriomazzeo** [comment]
I re-selected the Xcode app from the server app and now is working, weird...

**Comment by czechboy0** [comment]
Yeah, I think it re-initializes its internal platforms/SDKs. Glad it's working now, we will need to make that change in XcodeServerSDK anyway, to handle this case more gracefully. Thanks for reporting it! :+1:

**Comment by valeriomazzeo** [comment]
np! :+1:
