### ISSUE TITLE
GitHub API request rate seems wrong

### ISSUE THREAD

**Issue by joelekstrom** [czechboy0/Buildasaur#156]
![skarmavbild 2015-10-05 kl 17 27 11](https://cloud.githubusercontent.com/assets/1607453/10284869/7c7fc3ee-6b86-11e5-841c-afce2fc0d93b.png)

Looks a bit over the top to me.

**Comment by czechboy0** [comment]
Yeah I've seen this before as well. I think the data is coming down incorrectly from GitHub, but it's also possible I have a bug in my calculations.

It's a couple of lines of code, please let me know if I'm doing something stupid :) https://github.com/czechboy0/Buildasaur/blob/master/BuildaGitServer/GitHubRateLimit.swift

But, when you look at it, it _does_ make sense based on the data. Your example says it will renew in 3598 seconds, which means just 2 seconds elapsed, and the count is already at 185. So 185/2 = 92.5 requests per second (according to github) would really mean we're using a huge number of requests, even 12000% of what's allowed. At this pace, we'd be done in less than a minute :) That's why I think the rate limit headers from GitHub sometimes go bonkers (maybe when the reset hour just happened).

Again, any theories or fixes are welcome :)

**Comment by czechboy0** [comment]
I tried more debugging and it's definitely GitHub sending incorrect header values. Closing since it's not a Buildasaur bug (and hopefully we won't even be affected by it, other than making these rate-limit estimates useless sometimes).

**Comment by joelekstrom** [comment]
:+1: thanks for investigating
