### ISSUE TITLE
Cache git repo

### ISSUE THREAD

**Issue by russbishop** [czechboy0/Buildasaur#159]
I don't know if this is possible given the way Xcode server works but it seems really stupid that it deletes the entire git repo when you do a clean; most of my bots spend their time re-downloading the repo when they're all pointing at the same repo that rarely changes.

Do you think it would be possible to setup buildasaur to fetch the remote repo (all branches) to a local repo, then "push" those branches to Xcode's Server's hosted repo (which is just local traffic) and make the bots build from that source?

**Comment by czechboy0** [comment]
You can control the cleaning both in Buildasaur for your PR Bots and when creating one from Xcode. I think it makes sense it does a complete wipe when cleaning is on. So why don't you turn it off?

What you might also mean is that it's annoying that for every new Bot the repo has to be re-cloned. I agree, that has been a major slowdown on large projects I've worked on. Unfortunately, caching locally would require me to do a lot of hacking with the blueprint, authentication etc, which I feel like is beyond the scope of Buildasaur at the moment.

What I think **is** worth doing is reporting this to apple at bugreport.apple.com and ask them to make Xcode Server only do shallow copies (no history) of just one branch (the branch to track). That would speed up the cloning immensely. If you create the ticket, please put it on openradar and I'll gladly duplicate it. :+1:

**Comment by czechboy0** [comment]
Sorry @russbishop, I don't think there's anything I can realistically do to improve this issue. That's really an Xcode Server behavior - just please make sure your **cleaning policy** is set to **Never**, which will only clone your project once per bot. Unfortunately, there's no reasonable way to force XCS to reuse cloned working copies _between bots_.

Since there's nothing I can do atm, I'm closing this.

**Comment by ghost** [comment]
@russbishop not sure if this is still relevant, but I've solved the problem by using https://github.com/beefsack/git-mirror

**Comment by czechboy0** [comment]
@max-desiatov Interesting, are you using it with Buildasaur?

**Comment by ghost** [comment]
@czechboy0 I'm not finished with setting it up yet. But yes, Xcode bots cloning everything from scratch is only a problem with Buildasaur which creates new bots regularly. So without Buildasaur I'd never think about mirroring, but I don't see any other easy way to implement pull request checks without creating a new bot for each pull request.

**Comment by ghost** [comment]
Or an old bot could be reused, but I've noticed when anything about repositories is changed in bot settings (even changing a branch), that still causes it to clone everything again. Which is stupid. Let's hope Apple fixes this sooner rather than later.

**Comment by czechboy0** [comment]
Yeah that is sort of an issue, which is why I try to keep my repo sizes below 100MB, because large repos can take longer to check out than to build and test.

If you manage to get it working with Buildasaur, I'd be very interested in reading a post about that, I think I'd even link to it from my tutorials. So let me know if you decide to publish such a post.
