### ISSUE TITLE
Add UI To Update Existing Build Templates

### ISSUE THREAD

**Issue by grantjk** [czechboy0/Buildasaur#190]
When new iOS simulators are provided, it would be nice to be able to update existing templates rather than having to create new ones.

**Comment by czechboy0** [comment]
Not sure I understand - when you're editing/creating a syncer, you're presented with a list of existing Build Templates and there's an option to create a new Build Template. You _can_ select an existing Build Template, assuming it's for the same project (Build Templates cannot yet be reused between different projects, because they contain a scheme which is project-specific). Is this the same thing as #181?

**Comment by grantjk** [comment]
Right. Is there a way to update an existing template though? Say I want to change the devices the template has. Can I do this on an existing template without creating an entirely new template?

**Comment by czechboy0** [comment]
Yes, by clicking edit in the detail view and selecting the existing build
template from the list.

**Comment by grantjk** [comment]
Ah! Didn't realize that. My bad!
