### ISSUE TITLE
Device missing on OS X Project

### ISSUE THREAD

**Issue by valeriomazzeo** [czechboy0/Buildasaur#192]
When running configuring a template for an OS X project, buidasaur doesn't display the device where it needs to run.

The list of simulator is there, but they are all iPhone simulator. I'd be expecting to see something like: `My Mac` instead.

**Comment by czechboy0** [comment]
Make sure you're selecting the right scheme, because a scheme selects exactly one target and a target selects exactly one platform (OS X or iOS).

If you're seeing iOS simulators but are expecting Macs, your target must be an iOS target instead of a OS X target. 

Is there anything about the project you could share, so that I can test it locally?

**Comment by valeriomazzeo** [comment]
Fiddling with the scheme settings, when I select the iOS target it shows up the mac mini as device. Selecting back the OS X target shows up the iOS simulators :S

**Comment by valeriomazzeo** [comment]
Maybe it's just an UI problem?

Maybe the combobox doesn't display the name of the selected target or the list of the devices read from the wrong index?

**Comment by czechboy0** [comment]
Well that definitely looks like a bug :D weird that it worked fine for everyone else. Could you try to create a clean new project with just e.g. iOS project and see if Buildasaur shows the right type of device? Or is your project where you're seeing this issue an oss project by any chance?

**Comment by czechboy0** [comment]
Just btw, are you on the latest version?

**Comment by valeriomazzeo** [comment]
Target list as shown in my Xcode:
1) iOS
2) OS X
3) Watch OS

Target list as shown in buildasaur:
1) OS X
2) iOS
3) Watch OS

Selected iOS target -> shows OS X devices
Selected OS X target -> shows iOS devices
Selected Watch OS target -> shows nothing

if I selected the iOS Target and then press `Next`, the before the window disappear I can see the combobox name changing from `iOS` to `OS X`.

**Comment by valeriomazzeo** [comment]
yep, latest version

**Comment by czechboy0** [comment]
Just to clarify, those are schemes, not target names. 

But this sure looks like a bug. Could you try to reproduce with a new, clean project with just two target types? So that you could send me that, will make it much easier to fix. 

Thanks!

**Comment by valeriomazzeo** [comment]
Those are schemes, but the targets have the same name as well.

I'd love to, but I am not sure to have the time :S

Anyway, I think it's only an UI problem because the integration works :)

**Comment by czechboy0** [comment]
Hmm I can't reproduce it, it does sometimes take 2-3 seconds to properly change the devices (because I have to run a command to parse the target type with `NSTask`, which takes ages-seconds), but it ends up being the correct thing.

Can you try again and once you change the scheme, wait up to 5 seconds to see whether it changes? Maybe it's just slow.

**Comment by valeriomazzeo** [comment]
I did wait and it didn't change until I switched target

**Comment by czechboy0** [comment]
Duplicate, see #193 for a temporary workaround.
