### ISSUE TITLE
Sort devices by name and OS version

### ISSUE THREAD

**Issue by hallc** [czechboy0/Buildasaur#195]
The list of devices on the build template editor is not sorted by name or OS version.  Our Xcode server has quite a few simulators configured and it's difficult to pick out the ones we need to test a particular project against.

Sorting by name and OS version would make the list easier to read.

I can gladly submit a PR if this is a welcome change.

**Comment by czechboy0** [comment]
Hi @hallc,

thanks for taking time to report this. I wrote a function to somehow sort the devices ages ago and it's possible it doesn't work properly since my big refactoring for 0.6. It's [this](https://github.com/czechboy0/Buildasaur/blob/master/Buildasaur/BuildTemplateViewController.swift#L434) function, so feel free to make sure it works as you'd expect and contribute a PR!

Thanks!
