### ISSUE TITLE
Prebuild trigger cannot find project folder

### ISSUE THREAD

**Issue by natemann** [czechboy0/Buildasaur#252]
I am getting this error with Buildasaur bots.  All other bots are working properly.  I have tried adding `export LANG=eng_US.UTF-8` to the pre-build trigger, but this is not working.

**Comment by czechboy0** [comment]
Hi @natemann,

what's the exact failure message you're seeing?

**Comment by natemann** [comment]
@czechboy0, I think I have a different issue now.  The issue has nothing to do with Cocoapods.  Buildasaur cannot find my directory.  I do a cd into the project folder in a pre-trigger, but I get this error "No such file or directory".  I am using the same 'cd' command from my other bots

**Comment by czechboy0** [comment]
Ah, I think I know what it is. When you create a Bot manually in Xcode, it uses the same folder name as you have on disk, whereas Buildasaur uses the project name for the folder name.

Just change your first step of the trigger to a wildcard, because there will only be one folder: `cd *`. That's what I use as well. Let me know if that helped! :blush:

**Comment by natemann** [comment]
ok.  That is working, sort of.  When I create a new pull request, I am getting an error the first time (Linker command failed with exit code 1).  When I change a file in the pull request, and 'lttm', the build succeeds.

**Comment by natemann** [comment]
@thanks.  That did it.

**Comment by czechboy0** [comment]
Great!
