### ISSUE TITLE
Private Bitbucket Repo

### ISSUE THREAD

**Issue by nhaskins01** [czechboy0/Buildasaur#276]
@czechboy0 My company uses a private bitbucket repo with a custom url: stash.company.com . Is there anyway we can override the default bitbucket url? My company would really like to use buildasaur.. but this is obviously preventing us from using it

**Comment by czechboy0** [comment]
Hi @nhaskins01,

unfortunately BitBucket Server (self-hosted) isn't officially supported yet, but there is at least one fork with it working, so please take a look here: https://github.com/czechboy0/Buildasaur/network (I see at least two forks with bitbucket server).

But as you'd expect, if you have specific questions about their code, you'll need to talk to them directly.

**Comment by macdema** [comment]
@czechboy0 I also need private repo support. I'd rather not get tied to a forked repo for ongoing support as it seems there were significant changes between Xcode 6 and 7 which you had to update Buildasaur for and I expect the same to happen moving forward. I'd like to make my own build but it's asking for a BitBucketAPIClientId and BitBucketAPIClientSecret when I try to run `pod install` and I'm not sure what those are. Could you provide or explain how to get these keys so that I can compile my own Buildasaur until BitBucket Server is officially hosted?
