### ISSUE TITLE
Bitbucket Support

### ISSUE THREAD

**Issue by willsr** [czechboy0/Buildasaur#65]
Is there any merit in adding support for BitBucket pull requests into Buildasaur?

**Comment by czechboy0** [comment]
Depends, is there demand for it? I don't know how different BitBucket pull requests are to GitHub's, but if I see there might be enough interested people, it is something I would consider. 

Or even better would be if someone who has a bit of knowledge of how people use BitBucket vs GitHub did it.

**Comment by jaharabari** [comment]
I am also using BitBucket. if possible please add support for bitbucket too.

Thanks

**Comment by atljeremy** [comment]
:+1: for bitbucket support

**Comment by czechboy0** [comment]
It's starting to look like Bitbucket might be the second source server we'll support.
Docs: https://confluence.atlassian.com/bitbucket/version-2-423626329.html

**Comment by valeriomazzeo** [comment]
Definitely bitbucket and GitLab in the list

**Comment by dlbuckley** [comment]
Bitbucket support would be great.

**Comment by yakubbaev** [comment]
+1

**Comment by n0quarter** [comment]
+1

**Comment by czechboy0** [comment]
Okay, work on this has started. I'd appreciate if you all could write a couple of sentences about how you use the BitBucket PR workflow, how you'd compare it with GitHub's (if you've used both) and which features are the most important ones for you. I haven't personally used BB's PRs yet, so I'm learning as I go.

I'm investigating the API at the moment, but work in #185 is pretty much finished, so check out the branch hd/bitbucket if you're curious about the progress.

**Comment by czechboy0** [comment]
Okay, from initial research I have a couple of more unknowns and findings:
- [x] need to find how to do conditional requests, which were recently implemented for GitHub (#62), otherwise we'd be running out of request allowance
- [x] find out the actual rate limit, the docs are confusing
- [x] find how to programatically detect the rate limit to be able to gradually slow down if we approach it (not yet implemented but would be considered if the rate limit is low)
- [x] find out whether using both v1 and v2 of the API is not going to be a problem, unfortunately v2 is not yet feature complete, but it's much nicer to use for available calls
  - Should be fine.
- [x] find out whether there's a native PR/commit/branch build status like on GitHub that would nicely show the build/test status of the code (otherwise we'd have to rely purely on Buildasaur's comments, which is not as pretty)
  - Yes, added only very recently. https://confluence.atlassian.com/bitbucket/statuses-build-resource-779295267.html
- [x] find out the easiest but secure authentication method (Basic auth with a token like GitHub maybe? OAuth?)
  - Use OAuth2 with https://github.com/OAuthSwift/OAuthSwift
- [x] have xcodeproj parsing code recognize BitBucket URLs (both HTTPS and SSH) in addition to GitHub
- [x] add BB-specific error object parsing and pagination support (different to GitHub) described in https://confluence.atlassian.com/bitbucket/version-2-423626329.html

I looked at the API and most things should be easy to implement. Everything has been abstracted away so we only need to implement the communication with the API and all the syncing logic will be reused from the code managing GitHub projects.

If any of you have any comments/answers to the questions I have above, I'd be grateful for any help. At this stage I'll spend much more time on the research than on the implementation (that will be easy thanks to #185 and should open up the path to more server types that use PRs, like GitLab etc.).

**Comment by czechboy0** [comment]
Progress tracked in #217, for those who want to try an early build, **let me know**. I'll create a very early alpha for you manually. Everything seems to be working nicely, it's mostly just testing now and final polish.

**Comment by czechboy0** [comment]
Fixed by #217.

**Comment by czechboy0** [comment]
All you BitBucket people, the first beta is out here: https://github.com/czechboy0/Buildasaur/releases/tag/v1.0.0-b1
Please give it a try and provide feedback, thanks! (Ideally start syncing your bitbucket repo and give it a good stress test)

Also, you won't need to manually install new versions anymore, because Buildasaur will be able to autoupdate from now on.
