### ISSUE TITLE
Buildasaur immediately crashes after being started

### ISSUE THREAD

**Issue by st3fan** [czechboy0/Buildasaur#70]
Buildasaur immediately crashes after being started, Nothing in the logs. Is there a debug mode so that I can provide some more feedback?

**Comment by czechboy0** [comment]
That's not good, I've never seen that. It must fail something while loading its preferences in `~/Library/Application Support/Buildasaur`. To see if that's it, try renaming it to something like `Buildasaur2` so that it loads in a new, unconfigured mode. Let me know if that helped. 

Also, if you could send me the crash log from `~/Library/Logs/DiagnosticReports/Buildasaur-*` and the log from `~/Library/Application Support/Buildasaur/Builda.log`, that would be great. Please send it to czechboy069 at gmail. I'll take a look and let you know ASAP.

**Comment by czechboy0** [comment]
@st3fan Any news on this?

**Comment by st3fan** [comment]
I grabbed the source and built the last version. No more problems :-)

**Comment by czechboy0** [comment]
Ok, sorry about that (whatever it was). If this happens again, make sure to gather all the logs so that we can figure out what the problem was :) Closing for now.
