### ISSUE TITLE
Migrate to Swift 2

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/Buildasaur#76]
Blocks #69. Migrate over so that we can pull in the new version of [XcodeServerSDK](https://github.com/czechboy0/XcodeServerSDK).

**Comment by sofacoder** [comment]
Hi Honza,

are you currently working on this? Because I have it running in a very hacky state (and I'm especially unhappy with the way I did the new error handy part). And also I based it on your experimental Xcode 7 brach, so before the XcodeServerSDK was created. 

To make a long story short: I'm thinking about adding atlassian stash support to Buildasaur. So if you are working on Xcode 7 I will just wait, otherwise I could also put some effort into Xcode 7.

**Comment by czechboy0** [comment]
Hi @sofacoder, yeah actually last night I just got it to compile with Swift 2. But there are a couple of things I had to break (specifically the way you pick test devices) due to changes in XcodeServerSDK during migration to Xcode 7 API. I will be working on this branch now to fix them and mostly things in the UI will change.

To answer your question - if you'd like to add more git server support, feel free to start working of **this** branch, because it's already migrated to Swift 2 and it uses XcodeServerSDK. I plan no changes to the GitHub communication code, so that's probably what you'll be changing (somehow parse out common code between GitHub and Stash and add the differences).

And please keep me in the loop so that I know what parts of code to try to avoid changing now. And thanks for helping out with Buildasaur! :)

**Comment by sofacoder** [comment]
Ah, should have looked at the commit before commenting here. ;-)

Nice to see that you have this already working.

Ok, I will fork an base my stuff at this branch. No time indication yet, since the weather is good this week. ;-)

**Comment by czechboy0** [comment]
Yeah, I myself was out playing frisbee when you commented here (guilty as charged) :+1:

**Comment by czechboy0** [comment]
Migrated to Swift 2 on branch [hd/swift-2](https://github.com/czechboy0/Buildasaur/tree/hd/swift-2). Still experimental, will get merged together with #69.
